FROM amazonlinux:latest

MAINTAINER Bhartendu

RUN yum -y update && \
    yum -y install \
        python3.6 \
        pip \
        make \
        awscli\
        zip

ENV APP_HOME /my_project 

ENV APP_SRC $APP_HOME/src

RUN mkdir $APP_HOME

ADD . $APP_HOME

RUN pip install --no-deps -t $APP_SRC/lambda_package -r $APP_SRC/requirements.txt

RUN echo "Python Dependencies built"

