PROJECT = /zipped_lambda_package/
AWS_REGION = us-ohio-east
FUNCTION_HANDLER = lamda_handler
LAMBDA_ROLE = arn:aws:iam:991675433:role/service-role/lambda-basic-role
PROJECT_ZIP_NAME = package

lambda_function_create:
  aws lambda create-function \
  --region $(AWS_REGION) \
  --function-name $(FUNCTION_NAME) \
  --zip-file fileb:$(PROJECT)/$(PROJECT_ZIP_NAME).zip \
  --role $(LAMBDA_ROLE) \
  --handler $(PROJECT).$(FUNCTION_HANDLER) \
  --runtime python3.6 \
  --timeout 15 \
  --memory-size 120
